"""Built-in library entries: the manuscript's own tower geometries and
heliostat design, plus (docs/ui-spec-v0.2.md §P) four reconstructed
reference heliostat fields -- all read-only and always present
(docs/ui-spec.md 5).

Plain dict constants rather than the pydantic models :mod:`heliostat.web.app`
validates them against: this module has to be importable from
:mod:`heliostat.web.library`'s side of things without pulling in FastAPI/
pydantic, and a built-in is data, not behaviour. ``tests/test_web_library.py``
is the parity gate -- it validates every entry here through the matching
model in ``app.py`` *and* asserts the numbers equal that model's own
defaults, so this file and the app's module constants cannot silently drift
apart.

Numbers are copied from ``heliostat.web.app``'s optics defaults
(``PRIME_FOCUS_HEIGHT_MM`` and its neighbours), which are themselves copied
from ``examples/paper/reproduce.py`` -- see that module's docstring for
where each one comes from. Copied rather than imported for the same reason
``app._geometry_for`` does not import ``_geometry_for`` from the test suite:
a built-in library entry is content, not a physics dependency, and neither
script is a stable import surface for the other.
"""

from __future__ import annotations

from pathlib import Path

from heliostat.field import load_field

#: Receiver window half-extent, matching app.WINDOW_MM -- every built-in
#: receiver uses the library's own default window, since none of the three
#: manuscript layouts calls for a different one.
_WINDOW_MM = 2000.0

#: Where the packaged reference-field CSVs live -- siblings of
#: app.MANUSCRIPT_FIELD_PATH's field_645.csv, same directory, same
#: "committed data, parsed once" convention. Generated by
#: scripts/generate_reference_fields.py; see that script's module
#: docstring for the placement algorithm and every field's citations.
_DATA_DIR = Path(__file__).parent / "static" / "data"


def _reference_xy_mm(csv_name: str) -> list[list[float]]:
    """A packaged reference-field CSV's positions, in mm, rounded to 0.1 mm
    -- the same rounding :func:`heliostat.web.app.field_manuscript` reports
    the manuscript's own field at. Parsed at import time (module-level call
    below): these files never change at runtime, exactly like
    app._load_manuscript_field()'s own field_645.csv."""
    field = load_field(_DATA_DIR / csv_name)
    return [[round(float(x), 1), round(float(y), 1)] for x, y in field.xy_mm]

#: Receiver configs, keyed by display name. Each document is the shape
#: app.ReceiverDocument validates: which optics layout, and the params that
#: resolve against that layout's own model.
BUILTIN_RECEIVERS: dict[str, dict] = {
    "Prime focus 35.3 m": {
        "optics": "prime_focus",
        "params": {
            "focus_height_mm": 35335.0,
            "window_half_u_mm": _WINDOW_MM,
            "window_half_v_mm": _WINDOW_MM,
        },
    },
    "Axicon 27 m / 20 deg / 14 m": {
        "optics": "axicon",
        "params": {
            "apex_height_mm": 27000.0,
            "half_angle_deg": 20.0,
            "aperture_radius_mm": 14000.0,
            "receiver_z_mm": 7000.0,
            "window_half_u_mm": _WINDOW_MM,
            "window_half_v_mm": _WINDOW_MM,
        },
    },
    "Cassegrain relay": {
        "optics": "cassegrain",
        "params": {
            "vertex_z_mm": 26993.999446877,
            "focus_height_mm": 34892.4,
            "receiver_z_mm": 7000.0,
            "aperture_radius_mm": 14000.0,
            "window_half_u_mm": _WINDOW_MM,
            "window_half_v_mm": _WINDOW_MM,
        },
    },
}

#: The manuscript heliostat, 5 x 3 m, one entry per surface figure. Each
#: document is the shape app.DesignParams validates (a RectParams dict).
#: ``reflectance`` is the manuscript's own 90% mirror reflectance, spelled
#: out rather than left to the model's 100%-reflectance default; the other
#: three optical-error fields (slope, specularity, pointing -- §F) are
#: spelled out at their own (zero-error) default alongside it, so all four
#: read as deliberate choices rather than fields the built-in simply
#: predates.
BUILTIN_DESIGNS: dict[str, dict] = {
    f"Manuscript 5 x 3 m — {surface}": {
        "type": "rect",
        "width_mm": 5000.0,
        "height_mm": 3000.0,
        "surface": surface,
        "slope_error_mrad": 0.0,
        "specularity_mrad": 0.0,
        "reflectance": 0.9,
        "pointing_error_mrad": 0.0,
    }
    for surface in ("twisting", "spherical", "flat")
}

# ---------------------------------------------------------------------------
# docs/ui-spec-v0.2.md §P: four pre-built reference heliostat fields --
# Gemasolar, PS10, Crescent Dunes, and a Stellio-based field (Hami) -- each a
# labeled RECONSTRUCTION from published parameters, never the operator's own
# as-built layout (proprietary and unpublished for all four). This is the
# first use of the ``projects`` collection's built-in slot
# (``heliostat.web.library._BUILTIN_NAMES["projects"]`` was empty before
# this).
#
# Every field's positions come from scripts/generate_reference_fields.py's
# packaged CSVs (parsed once, at import time, below) -- a committed,
# reproducible generator, not hand-typed coordinates; see that script's
# module docstring for the placement algorithm and every number's source.
# Design/receiver/sun parameters here carry their own citations in
# BUILTIN_PROJECT_PROVENANCE, keyed by the same display name, since
# app.ProjectDocument (``extra="forbid"``) has no field to carry provenance
# text on the document itself -- app.py's library-load endpoint attaches it
# alongside the document instead (see BUILTIN_PROJECT_PROVENANCE's own
# docstring below).
#
# Every design is an IDEAL BUILD (docs/ui-spec-v0.2.md §P, binding):
# slope_error_mrad, specularity_mrad and pointing_error_mrad all 0, so what
# renders is the layout/geometry's own performance, not a guess at a real
# plant's error budget. reflectance is 0.90 for all four -- this app's
# standard convention (BUILTIN_DESIGNS' own manuscript value above), not a
# plant-specific published number for any of them; disclosed as such in
# each entry's provenance caveats.

_GEMASOLAR_XY_MM = _reference_xy_mm("field_gemasolar.csv")
_PS10_XY_MM = _reference_xy_mm("field_ps10.csv")
_CRESCENT_DUNES_XY_MM = _reference_xy_mm("field_crescent_dunes.csv")
_HAMI_XY_MM = _reference_xy_mm("field_hami.csv")

#: Shared by every built-in project design below -- see the ideal-build note
#: above.
_IDEAL_ERRORS = {
    "slope_error_mrad": 0.0,
    "specularity_mrad": 0.0,
    "reflectance": 0.9,
    "pointing_error_mrad": 0.0,
}

BUILTIN_PROJECTS: dict[str, dict] = {
    # -- Gemasolar (Torresol Energy, Fuentes de Andalucia, Spain) -----------
    # 2650 heliostats, 11.5 x 10.4 m mirror (7x5 facets), 140 m tower,
    # 14.22 m external cylindrical molten-salt receiver: DOCUMENTED
    # (HelioCon, citing the Sener spec sheet; Wikipedia). See
    # BUILTIN_PROJECT_PROVENANCE["Gemasolar (reconstruction)"] for the full
    # citation and disclosed approximations (receiver diameter inferred;
    # field is circularly symmetric, not the real N/S/E-W asymmetric
    # footprint).
    "Gemasolar (reconstruction)": {
        "schema_version": 2,
        "design": {
            "type": "grid",
            "n_u": 7,
            "n_v": 5,
            "facet_w_mm": 1617.142857,
            "facet_h_mm": 2056.0,
            "gap_mm": 30.0,
            **_IDEAL_ERRORS,
        },
        "receiver": {
            "optics": "prime_focus",
            "params": {
                "receiver_type": "cylinder",
                "focus_height_mm": 132890.0,
                "cylinder_radius_mm": 4250.0,
                "cylinder_height_mm": 14220.0,
            },
        },
        "field": {"layout": {"type": "positions", "xy_mm": _GEMASOLAR_XY_MM}},
        "sun": {
            "azimuth_deg": 122.521,
            "elevation_deg": 67.295,
            "site": {
                "latitude_deg": 37.558086,
                "longitude_deg": -5.329056,
                "timezone_h": 1.0,
                "year": 2026,
                "month": 6,
                "day": 21,
                "hour": 12.0,
            },
        },
        "run": {"mode": "ultra_fast"},
        "runs": [],
    },
    # -- PS10 (Abengoa/Solucar, Sanlucar la Mayor, Spain) --------------------
    # 624 heliostats, cavity receiver (4 vertical panels, 5.5 x 12 m each),
    # north (polar) field: DOCUMENTED (Wikipedia, Modern Power Systems). See
    # BUILTIN_PROJECT_PROVENANCE["PS10 (reconstruction)"] -- most notably,
    # Coddington has no tilted/oriented receiver window (spec §I, signed off
    # but not yet built), so this ships with a flat HORIZONTAL window
    # instead of PS10's real ~12.5-degree-from-vertical cavity face; a
    # disclosed approximation, not a claim that §I was built for this rider.
    "PS10 (reconstruction)": {
        "schema_version": 2,
        "design": {
            "type": "rect",
            "width_mm": 10977.25,
            "height_mm": 10977.25,
            **_IDEAL_ERRORS,
        },
        "receiver": {
            "optics": "prime_focus",
            "params": {
                "receiver_type": "flat",
                "focus_height_mm": 90000.0,
                "window_half_u_mm": 11000.0,
                "window_half_v_mm": 6000.0,
            },
        },
        "field": {"layout": {"type": "positions", "xy_mm": _PS10_XY_MM}},
        "sun": {
            "azimuth_deg": 120.787,
            "elevation_deg": 66.736,
            "site": {
                "latitude_deg": 37.4292,
                "longitude_deg": -6.2569,
                "timezone_h": 1.0,
                "year": 2026,
                "month": 6,
                "day": 21,
                "hour": 12.0,
            },
        },
        "run": {"mode": "ultra_fast"},
        "runs": [],
    },
    # -- Crescent Dunes (SolarReserve, Tonopah, Nevada) ----------------------
    # 10347 heliostats, 10.8 x 10.8 m mirror (7x5 facets), 195 m tower,
    # external cylindrical molten-salt receiver: DOCUMENTED (HelioCon, Power
    # Technology). See
    # BUILTIN_PROJECT_PROVENANCE["Crescent Dunes (reconstruction)"] --
    # receiver height/diameter are inferred (not published), and field
    # extent is generator-determined, not fit to a land-area figure this
    # rider's research found unreliable.
    "Crescent Dunes (reconstruction)": {
        "schema_version": 2,
        "design": {
            "type": "grid",
            "n_u": 7,
            "n_v": 5,
            "facet_w_mm": 1517.142857,
            "facet_h_mm": 2136.0,
            "gap_mm": 30.0,
            **_IDEAL_ERRORS,
        },
        "receiver": {
            "optics": "prime_focus",
            "params": {
                "receiver_type": "cylinder",
                "focus_height_mm": 185000.0,
                "cylinder_radius_mm": 5900.0,
                "cylinder_height_mm": 20000.0,
            },
        },
        "field": {"layout": {"type": "positions", "xy_mm": _CRESCENT_DUNES_XY_MM}},
        "sun": {
            "azimuth_deg": 187.731,
            "elevation_deg": 75.088,
            "site": {
                "latitude_deg": 38.239,
                "longitude_deg": -117.363,
                "timezone_h": -8.0,
                "year": 2026,
                "month": 6,
                "day": 21,
                "hour": 12.0,
            },
        },
        "run": {"mode": "ultra_fast"},
        "runs": [],
    },
    # -- Stellio-based field (Hami, CEEC/sbp, Xinjiang, China) ---------------
    # 14500 heliostats (sbp's own official number -- see provenance for the
    # disputed 14,000-15,000 range), 220 m tower, external cylindrical
    # molten-salt receiver. Heliostat outline is a regular pentagon (a
    # single 5-vertex `custom` polygon facet, circumradius 4469.65 mm) sized
    # to Stellio's documented ~47.5 m^2 reflective area exactly (shoelace
    # area 47.4999... m^2) -- an approximation of the real trapezoidal-panel
    # pentagon around a central hub, disclosed in
    # BUILTIN_PROJECT_PROVENANCE["Stellio-based field (reconstruction)"]
    # alongside the tracking-kinematics caveat (Coddington's reflection-law
    # aiming does not model Stellio's "two inclined axes", and whether that
    # is equivalent to target-aligned tracking is unconfirmed either way).
    #
    # JUDGMENT CALL: geometry/design.py's flower(n_petals=5, ...) -- a
    # rounded vesica-lens-petal shape -- was the primitive
    # docs/ui-spec-v0.2.md §P's research flagged as the closest existing
    # vocabulary match, and was this file's first draft. Switched to a
    # plain custom polygon for two reasons found while wiring this project
    # into the live workspace: (1) the app's own Heliostat panel and
    # project-load/save path (js/project.js's DESIGN_TYPES) do not yet
    # support the "flower" design type at all -- only rect/grid/custom --
    # so a flower-based project could be served but never actually opened
    # in the workspace; (2) a straight-edged regular pentagon is, if
    # anything, a literally closer "pentagonal outline" than flower()'s
    # rounded, concave-between-petals silhouette. Neither shape reproduces
    # the real panel's trapezoidal-facet/hub structure; this one is a
    # single flat facet, disclosed as such.
    "Stellio-based field (reconstruction)": {
        "schema_version": 2,
        "design": {
            "type": "custom",
            "vertices_mm": [
                [0.0, 4469.65],
                [-4250.89, 1381.2],
                [-2627.2, -3616.02],
                [2627.2, -3616.02],
                [4250.89, 1381.2],
            ],
            **_IDEAL_ERRORS,
        },
        "receiver": {
            "optics": "prime_focus",
            "params": {
                "receiver_type": "cylinder",
                "focus_height_mm": 200000.0,
                "cylinder_radius_mm": 6700.0,
                "cylinder_height_mm": 40000.0,
            },
        },
        "field": {"layout": {"type": "positions", "xy_mm": _HAMI_XY_MM}},
        "sun": {
            "azimuth_deg": 125.671,
            "elevation_deg": 60.938,
            "site": {
                "latitude_deg": 43.613785,
                "longitude_deg": 94.956374,
                "timezone_h": 8.0,
                "year": 2026,
                "month": 6,
                "day": 21,
                "hour": 12.0,
            },
        },
        "run": {"mode": "ultra_fast"},
        "runs": [],
    },
}

#: Provenance metadata for each ``BUILTIN_PROJECTS`` entry, keyed by the
#: same display name. Not part of the ``ProjectDocument`` schema (which
#: forbids extra fields, same as every other library document) -- kept
#: alongside it here so ``heliostat.web.app``'s library-load endpoint can
#: attach it to the response without touching the document a project
#: actually loads into the workspace. ``library_list``/``library_load``
#: return this verbatim; ``library.js`` renders ``citation`` and
#: ``caveats`` on the card (docs/ui-spec-v0.2.md §P's binding provenance
#: requirement) and stamps ``citation`` into the top bar while the project
#: is open.
#:
#: Every citation and caveat below is carried over from the session's
#: research pass (see scratchpad/reference_fields_research.md, referenced
#: from docs/ui-spec-v0.2.md §P) -- confidence labels (DOCUMENTED / WIDELY
#: REPORTED / INFERRED) from that pass are folded into the prose rather
#: than re-labeled here, so a disputed or inferred number reads as such,
#: not picked silently.
BUILTIN_PROJECT_PROVENANCE: dict[str, dict] = {
    "Gemasolar (reconstruction)": {
        "reconstruction": True,
        "field_kind": "Surround field",
        "heliostat_count": 2650,
        "receiver_summary": "140 m tower · external cylindrical molten-salt receiver",
        "citation": (
            "Reconstruction from published parameters (heliostat count, 11.5 x 10.4 m "
            "mirror, 7x5 facets, 14.22 m receiver height: HelioCon, citing the Sener spec "
            "sheet; 140 m tower: HelioCon, Wikipedia). Not the operator's as-built layout -- "
            "exact heliostat coordinates are proprietary and unpublished."
        ),
        "caveats": [
            "Circularly symmetric only: real Gemasolar is denser to the north than south "
            "(published asymmetry, ~870 m N / ~550 m S / ~735 m E-W) -- this app's "
            "radial-staggered layout applies one ring-radius list at every azimuth and "
            "cannot reproduce that asymmetry.",
            "Receiver diameter (~8.5 m) is not published; inferred as a typical "
            "external-cylindrical-receiver proportion, not a sourced Gemasolar number.",
            "Mirror reflectance (0.90) is this app's standard convention (matching the "
            "manuscript built-in design), not a Gemasolar-specific published value.",
        ],
    },
    "PS10 (reconstruction)": {
        "reconstruction": True,
        "field_kind": "North (polar) field",
        "heliostat_count": 624,
        "receiver_summary": "115 m tower (disputed, see caveats) · cavity receiver, flat window approximation",
        "citation": (
            "Reconstruction from published parameters (624 heliostats, ~120-121 m^2 mirror "
            "unit area: Wikipedia, Modern Power Systems; cavity receiver, 4 vertical panels "
            "5.5 x 12 m each: Modern Power Systems). Tower height reported as 115 m "
            "(Wikipedia) or 120 m (Modern Power Systems) -- this build uses 115 m; the "
            "dispute is not resolved here. Not the operator's as-built layout."
        ),
        "caveats": [
            "This app's receiver model has no tilted/oriented window yet. PS10's real cavity "
            "aperture faces the north field at roughly 12.5 degrees from vertical (as-built); "
            "this field ships with a flat, HORIZONTAL window instead, sized to the real "
            "cavity's approximate 22 x 12 m aperture -- the best available approximation "
            "today, not the true tilted cavity face.",
            "Mirror dimensions are not published (only the ~120 m^2 unit area); "
            "approximated here as a 10.98 m square single flat facet -- PS10's real facet "
            "subdivision is not modeled.",
            "North-sector angular span (+-60 degrees) is not a published PS10 number -- it "
            "reuses this app's own default half-span for consistency, not a sourced figure.",
            "Mirror reflectance (0.90) is this app's standard convention, not a "
            "PS10-specific published value.",
        ],
    },
    "Crescent Dunes (reconstruction)": {
        "reconstruction": True,
        "field_kind": "Surround field",
        "heliostat_count": 10347,
        "receiver_summary": "195 m tower · external cylindrical molten-salt receiver",
        "citation": (
            "Reconstruction from published parameters (10,347 heliostats, 10.8 x 10.8 m "
            "mirror, 7x5 facets, 195 m tower, external cylindrical molten-salt receiver: "
            "HelioCon, Power Technology). Not the operator's as-built layout."
        ),
        "caveats": [
            "Receiver height (~20 m) and diameter (~11.8 m) are not published; inferred "
            "proportionally from Gemasolar's documented receiver, scaled by tower height -- "
            "not a sourced Crescent Dunes number.",
            "Field extent is algorithmically generated to reach the documented heliostat "
            "count, not fit to a specific published land-area figure -- the one land-area "
            "number found (1,197,148 m^2) coincides suspiciously closely with the documented "
            "mirror unit area times heliostat count and is not trusted here.",
            "Mirror reflectance (0.90) is this app's standard convention, not a "
            "Crescent-Dunes-specific published value.",
        ],
    },
    "Stellio-based field (reconstruction)": {
        "reconstruction": True,
        "field_kind": "Surround field",
        "heliostat_count": 14500,
        "receiver_summary": "220 m tower (single source) · external cylindrical molten-salt receiver",
        "citation": (
            "Reconstruction from published Stellio heliostat and Hami plant parameters "
            "(pentagonal heliostat, ~47.5 m^2 reflective area: sbp's own tracking-quality "
            "spec page; Hami plant, 220 m tower: HelioCon, single source; 50 MW / 22 h "
            "storage: SolarPACES, PowerMag). Heliostat count reported as 14,500 (sbp's own "
            "official number, used here), 14,000 (HelioCon) or 15,000 (SolarPACES, "
            "PowerMag) -- sources disagree and this reconstruction does not resolve it. Not "
            "the operator's as-built layout."
        ),
        "caveats": [
            "Heliostat outline is a regular pentagon (a single flat custom-polygon facet, "
            "not a faceted flower/petal shape), circumradius 4.47 m, area matched exactly to "
            "the documented ~47.5 m^2 reflective area -- an approximation of the real "
            "Stellio panel, which is built from trapezoidal float-glass panels around a "
            "central hub with multiple facets, not one flat pentagon. Matching the area "
            "gives a circumdiameter of ~8.9 m, larger than a separate, weaker HelioCon "
            "estimate of ~7.9 m (likely back-calculated from the same area figure by a "
            "different assumption) -- the two published-ish numbers are not simultaneously "
            "consistent, and this reconstruction does not resolve that, it just discloses "
            "it. Not a geometric reconstruction of the real facet layout.",
            "Tracking kinematics are not reproduced. Stellio uses 'two inclined axes' "
            "(documented), driven by two linear actuators; whether that is equivalent to "
            "target-aligned tracking is NOT confirmed by any available source "
            "(Stellio's astigmatism benefit is attributed to the pentagon's shape, "
            "not the tracking, in the manufacturer's own material). This app's aiming model "
            "computes every facet's normal from the reflection law and does not model "
            "physical drive axes at all -- this field reproduces the field geometry and "
            "heliostat outline only, not Stellio's real tracking behavior.",
            "Receiver height (~40 m) and diameter (~13.4 m) rest on a single-source tower "
            "height; diameter is inferred proportionally, not sourced.",
            "Mirror reflectance (0.90) is this app's standard convention, not a "
            "Stellio-specific published value.",
        ],
    },
}
