"""Tests for heliostat.solar.

The numeric pins in ``TestReferenceValues`` were generated by running the
*original* research-codebase implementation of this module directly (pure
numpy, no external dependencies) for site lat=-9.4, lon=-40.5, tz=-3 on
2026-03-21 and 2026-12-21 at local hours 8.0, 12.0, 16.0, and hard-coded here.
They anchor port fidelity: if this module is ever touched, these values must
still reproduce to 1e-9.
"""

from __future__ import annotations

import datetime as dt

import numpy as np
import pytest

from heliostat import solar

LAT, LON, TZ = -9.4, -40.5, -3

# (date) -> (sunrise_hour, sunset_hour)
SUNRISE_SUNSET = {
    (2026, 3, 21): (5.766451000632633, 17.870174692181042),
    (2026, 12, 21): (5.333065885386717, 18.00489994727641),
}

# (date, hour) -> (azimuth_deg, elevation_deg)
SUN_POSITION = {
    (2026, 3, 21, 8.0): (83.62255946302793, 32.18033509690827),
    (2026, 3, 21, 12.0): (344.37849908973374, 79.83296831365367),
    (2026, 3, 21, 16.0): (275.32515725068043, 26.81189897856987),
    (2026, 12, 21, 8.0): (112.18164705843827, 35.752458015534806),
    (2026, 12, 21, 12.0): (198.08858201367377, 75.18556314046899),
    (2026, 12, 21, 16.0): (248.40749697387116, 26.666617386754833),
}

# (date, hour) -> (declination_deg, hour_angle_deg)
DECL_HA = {
    (2026, 3, 21, 8.0): (0.3353991124297572, -57.287105847262694),
    (2026, 3, 21, 12.0): (0.4012331438052502, 2.725307303897438),
    (2026, 3, 21, 16.0): (0.46705817424391555, 62.737731488277376),
    (2026, 12, 21, 8.0): (-23.437182094017146, -55.014096786734854),
    (2026, 12, 21, 12.0): (-23.437607889718393, 4.96525625502656),
    (2026, 12, 21, 16.0): (-23.437815746437252, 64.94460457596165),
}

DATES = [(2026, 3, 21), (2026, 12, 21)]
HOURS = [8.0, 12.0, 16.0]


class TestReferenceValues:
    """Pinned outputs from the original implementation, to 1e-9."""

    @pytest.mark.parametrize("date", DATES)
    def test_sunrise_sunset(self, date):
        y, m, d = date
        rise, set_ = solar.sunrise_sunset(LAT, LON, TZ, y, m, d)
        exp_rise, exp_set = SUNRISE_SUNSET[date]
        assert rise == pytest.approx(exp_rise, abs=1e-9)
        assert set_ == pytest.approx(exp_set, abs=1e-9)

    @pytest.mark.parametrize("date", DATES)
    @pytest.mark.parametrize("hour", HOURS)
    def test_sun_position(self, date, hour):
        y, m, d = date
        az, el = solar.sun_position(LAT, LON, TZ, y, m, d, hour)
        exp_az, exp_el = SUN_POSITION[(*date, hour)]
        assert az == pytest.approx(exp_az, abs=1e-9)
        assert el == pytest.approx(exp_el, abs=1e-9)

    @pytest.mark.parametrize("date", DATES)
    @pytest.mark.parametrize("hour", HOURS)
    def test_declination_hour_angle(self, date, hour):
        y, m, d = date
        dec, ha = solar.declination_hour_angle(LAT, LON, TZ, y, m, d, hour)
        exp_dec, exp_ha = DECL_HA[(*date, hour)]
        assert dec == pytest.approx(exp_dec, abs=1e-9)
        assert ha == pytest.approx(exp_ha, abs=1e-9)


class TestScalarArrayConsistency:
    def test_sun_position_scalar_vs_array(self):
        y, m, d = 2026, 3, 21
        az_s, el_s = solar.sun_position(LAT, LON, TZ, y, m, d, 12.0)
        az_a, el_a = solar.sun_position(LAT, LON, TZ, y, m, d, np.array([12.0]))
        assert az_a.shape == (1,)
        assert el_a.shape == (1,)
        assert float(az_a[0]) == pytest.approx(az_s, abs=1e-12)
        assert float(el_a[0]) == pytest.approx(el_s, abs=1e-12)

    def test_declination_hour_angle_scalar_vs_array(self):
        y, m, d = 2026, 12, 21
        dec_s, ha_s = solar.declination_hour_angle(LAT, LON, TZ, y, m, d, 8.0)
        dec_a, ha_a = solar.declination_hour_angle(LAT, LON, TZ, y, m, d, np.array([8.0]))
        assert float(dec_a[0]) == pytest.approx(dec_s, abs=1e-12)
        assert float(ha_a[0]) == pytest.approx(ha_s, abs=1e-12)

    def test_sun_position_array_of_many(self):
        y, m, d = 2026, 3, 21
        hours = np.array(HOURS)
        az_a, el_a = solar.sun_position(LAT, LON, TZ, y, m, d, hours)
        for i, h in enumerate(HOURS):
            az_s, el_s = solar.sun_position(LAT, LON, TZ, y, m, d, h)
            assert float(az_a[i]) == pytest.approx(az_s, abs=1e-12)
            assert float(el_a[i]) == pytest.approx(el_s, abs=1e-12)


class TestSampleHours:
    def test_edges_always_included(self):
        hours = solar._sample_hours(rise=6.0, set_=18.0, margin=0.5, step=1.0)
        assert hours[0] == pytest.approx(6.5)
        assert hours[-1] == pytest.approx(17.5)

    def test_spacing_never_exceeds_step(self):
        hours = solar._sample_hours(rise=6.0, set_=18.0, margin=0.5, step=1.0)
        spacing = np.diff(hours)
        assert np.all(spacing <= 1.0 + 1e-12)

    def test_empty_when_margin_eats_the_day(self):
        hours = solar._sample_hours(rise=6.0, set_=6.4, margin=0.5, step=1.0)
        assert hours.shape == (0,)
        assert hours.dtype == float

    def test_empty_when_margin_exactly_eats_the_day(self):
        # span == 0 exactly -- still empty, not a single degenerate point.
        hours = solar._sample_hours(rise=6.0, set_=7.0, margin=0.5, step=1.0)
        assert hours.shape == (0,)

    def test_step_smaller_than_span_produces_multiple_intervals(self):
        hours = solar._sample_hours(rise=0.0, set_=10.0, margin=0.0, step=3.0)
        # span=10, step=3 -> ceil(10/3)=4 intervals -> 5 points
        assert hours.shape == (5,)
        assert hours[0] == pytest.approx(0.0)
        assert hours[-1] == pytest.approx(10.0)
        assert np.all(np.diff(hours) <= 3.0 + 1e-12)


class TestHhmmAndTimeStep:
    def test_hhmm_basic(self):
        assert solar._hhmm(7.5) == (7, 30)
        assert solar._hhmm(0.0) == (0, 0)

    def test_hhmm_rollover_at_59_5_minutes(self):
        # 7 + 59.5/60 minutes rounds to (7, 60) internally -> rolls to (8, 0)
        hour = 7 + 59.5 / 60.0
        assert solar._hhmm(hour) == (8, 0)

    def test_hhmm_just_below_rollover(self):
        hour = 7 + 59.4 / 60.0
        assert solar._hhmm(hour) == (7, 59)

    def test_timestep_key_and_label(self):
        ts = solar.TimeStep(
            date=dt.date(2026, 3, 20),
            hour=7.5,
            solar_az_deg=90.0,
            solar_el_deg=30.0,
        )
        assert ts.key == "20260320_0730"
        assert ts.label == "2026-03-20 07:30"

    def test_timestep_key_rollover(self):
        ts = solar.TimeStep(
            date=dt.date(2026, 3, 20),
            hour=7 + 59.5 / 60.0,
            solar_az_deg=90.0,
            solar_el_deg=30.0,
        )
        assert ts.key == "20260320_0800"
        assert ts.label == "2026-03-20 08:00"

    def test_timestep_solar_ze_deg(self):
        ts = solar.TimeStep(
            date=dt.date(2026, 3, 20),
            hour=12.0,
            solar_az_deg=0.0,
            solar_el_deg=60.0,
        )
        assert ts.solar_ze_deg == pytest.approx(30.0)

    def test_timestep_str(self):
        ts = solar.TimeStep(
            date=dt.date(2026, 3, 20),
            hour=7.5,
            solar_az_deg=90.1,
            solar_el_deg=30.2,
        )
        s = str(ts)
        assert "2026-03-20 07:30" in s
        assert "az 90.1" in s
        assert "el 30.2" in s
