"""Tests for heliostat.geometry.shading.

Three kinds of coverage:

(a) The hand-checkable cases from :func:`heliostat.geometry.shading.self_check`,
    split into individual pytest functions for isolated failure reporting,
    plus one smoke test that runs the whole battery.
(b) Fixture parity: :mod:`tests.fixtures.shading` was generated by the
    private source research code's field + shading modules on the real
    field file.
    ``geometry.csv`` carries enough of the scene (target heliostats and
    every neighbour that fed into their numbers) to rebuild it exactly with
    the PUBLIC module and reproduce ``occlusion.csv`` to 1e-9.
(c) The union-vs-product regression: :func:`occlusion_efficiency`'s union
    must exceed ``eta_shade * eta_block`` on an overlapping-occlusion case,
    and the two must differ measurably (not just by float noise).
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from heliostat.field import HeliostatField, neighbour_pairs
from heliostat.geometry.shading import (
    MirrorGeometry,
    SecondaryCone,
    _fraction_unoccluded,
    build_geometries,
    corner_shadow,
    occlusion_efficiency,
    self_check,
    shading_blocking,
    sun_vector,
)

FIXTURES_ROOT = Path(__file__).parent / "fixtures"
SHADING_ROOT = FIXTURES_ROOT / "shading"


# ---------------------------------------------------------------------------
# (a) self_check's cases, as isolated pytest tests
# ---------------------------------------------------------------------------


def test_self_check_battery_passes():
    """Smoke test: the whole hand-checkable battery, in one call."""
    assert self_check(verbose=False)


def test_fully_occluded_mirror_sees_no_sun():
    target = MirrorGeometry.build(0, 0, 90.0, 45.0, 2500, 1500)
    to_sun = sun_vector(180.0, 10.0)
    occ_centre = target.centre + to_sun * 8000.0
    u = np.cross(np.array([0.0, 0.0, 1.0]), -to_sun)
    u /= np.linalg.norm(u)
    v = np.cross(-to_sun, u)
    occluder = MirrorGeometry(
        centre=occ_centre, normal=-to_sun, u=u, v=v, half_width=20000, half_height=20000
    )
    frac = _fraction_unoccluded(target.sample_points(), to_sun, [occluder])
    assert abs(frac) < 1e-9


def test_distant_occluder_does_not_shade():
    target = MirrorGeometry.build(0, 0, 90.0, 45.0, 2500, 1500)
    to_sun = sun_vector(180.0, 10.0)
    occ_centre = target.centre + to_sun * 8000.0
    u = np.cross(np.array([0.0, 0.0, 1.0]), -to_sun)
    u /= np.linalg.norm(u)
    v = np.cross(-to_sun, u)
    far = MirrorGeometry(
        centre=occ_centre + np.array([500000.0, 0.0, 0.0]),
        normal=-to_sun,
        u=u,
        v=v,
        half_width=2500,
        half_height=1500,
    )
    frac = _fraction_unoccluded(target.sample_points(), to_sun, [far])
    assert abs(frac - 1.0) < 1e-9


def test_occluder_behind_target_does_not_shade():
    target = MirrorGeometry.build(0, 0, 90.0, 45.0, 2500, 1500)
    to_sun = sun_vector(180.0, 10.0)
    u = np.cross(np.array([0.0, 0.0, 1.0]), -to_sun)
    u /= np.linalg.norm(u)
    v = np.cross(-to_sun, u)
    behind = MirrorGeometry(
        centre=target.centre - to_sun * 8000.0,
        normal=-to_sun,
        u=u,
        v=v,
        half_width=20000,
        half_height=20000,
    )
    frac = _fraction_unoccluded(target.sample_points(), to_sun, [behind])
    assert abs(frac - 1.0) < 1e-9


@pytest.mark.parametrize("rot_az,rot_el", [(2.0, 28.0), (20.0, 21.0), (-15.0, 40.0)])
def test_aligned_pair_matches_closed_form_overlap(rot_az, rot_el):
    """Parallel mirrors displaced by a fixed offset: shaded fraction is the
    closed-form rectangle overlap, not merely between 0 and 1."""
    to_sun = sun_vector(88.0, 9.71)
    hw, hh = 2500.0, 1500.0
    g = MirrorGeometry.build(0.0, 0.0, rot_az, rot_el, hw, hh)
    shift = to_sun * 6000.0
    shift[2] = 0.0
    occ = MirrorGeometry.build(shift[0], shift[1], rot_az, rot_el, hw, hh)

    t = float((occ.centre - g.centre) @ occ.normal / (to_sun @ occ.normal))
    off = (g.centre + t * to_sun) - occ.centre
    overlap = max(0.0, 1.0 - abs(off @ occ.u) / (2 * hw)) * max(
        0.0, 1.0 - abs(off @ occ.v) / (2 * hh)
    )
    exact = 1.0 - overlap

    n = 401
    got = _fraction_unoccluded(g.sample_points(n, n), to_sun, [occ])
    assert abs(got - exact) < 2.5 / n
    assert exact < 0.9  # guard against a case that shades nothing

    deeper = [
        MirrorGeometry.build(shift[0] * k, shift[1] * k, rot_az, rot_el, hw, hh)
        for k in range(1, 5)
    ]
    saturated = _fraction_unoccluded(g.sample_points(n, n), to_sun, deeper)
    assert abs(saturated - got) < 1e-12  # shading saturates at the nearest neighbour


def test_ground_shadow_polygons_agree_with_ray_sampling():
    to_sun = sun_vector(88.0, 9.71)
    hw, hh, pedestal = 2500.0, 1500.0, 5000.0
    g = MirrorGeometry.build(0.0, 0.0, 4.0, 26.0, hw, hh, pedestal)
    shift = to_sun * 6000.0
    shift[2] = 0.0
    occs = [
        MirrorGeometry.build(shift[0] * k, shift[1] * k, 4.0, 26.0, hw, hh, pedestal)
        for k in (1, 2)
    ]
    sampled = _fraction_unoccluded(g.sample_points(301, 301), to_sun, occs)

    tgt = corner_shadow(g, to_sun)[:, :2]
    n = 301
    a, b = np.meshgrid((np.arange(n) + 0.5) / n, (np.arange(n) + 0.5) / n, indexing="ij")
    grid = tgt[0] + a.ravel()[:, None] * (tgt[1] - tgt[0]) + b.ravel()[:, None] * (tgt[3] - tgt[0])
    covered = np.zeros(len(grid), dtype=bool)
    for occ in occs:
        q = corner_shadow(occ, to_sun)[:, :2]
        edge = np.roll(q, -1, axis=0) - q
        side = np.sign(np.cross(edge[None, :, :], grid[:, None, :] - q[None, :, :]))
        covered |= np.all(side >= 0, axis=1) | np.all(side <= 0, axis=1)
    polygon = 1.0 - covered.mean()
    assert abs(polygon - sampled) < 1e-9


def test_pedestal_height_does_not_change_mutual_shading():
    to_sun = sun_vector(88.0, 9.71)
    hw, hh = 2500.0, 1500.0
    shift = to_sun * 6000.0
    shift[2] = 0.0
    heights = []
    for z in (0.0, 5000.0, 20000.0):
        gz = MirrorGeometry.build(0.0, 0.0, 4.0, 26.0, hw, hh, z)
        oz = [
            MirrorGeometry.build(shift[0] * k, shift[1] * k, 4.0, 26.0, hw, hh, z) for k in (1, 2)
        ]
        heights.append(_fraction_unoccluded(gz.sample_points(101, 101), to_sun, oz))
    assert max(heights) - min(heights) < 1e-12


def test_blocking_uses_per_point_direction_and_it_matters():
    hw, hh = 2500.0, 1500.0
    aim = np.array([0.0, 0.0, 27000.0])
    g = MirrorGeometry.build(80000.0, 0.0, 4.0, 14.0, hw, hh)
    occs = [MirrorGeometry.build(80000.0 - 6000.0, 0.0, 4.0, 14.0, hw, hh)]
    pts = g.sample_points(101, 101)
    collimated = _fraction_unoccluded(pts, aim - g.centre, occs)
    converging = _fraction_unoccluded(pts, aim - pts, occs)

    slow = np.mean([_fraction_unoccluded(p[None, :], aim - p, occs) for p in pts[::37]])
    reference = _fraction_unoccluded(pts[::37], aim - pts[::37], occs)

    assert abs(collimated - converging) > 1e-3  # the correction is real
    assert 0.02 < converging < 0.98  # and the case actually blocks
    assert abs(reference - slow) < 1e-12  # vectorisation is faithful


def test_secondary_cone_hit_miss_and_shadow_band():
    cone = SecondaryCone(z_tip_mm=27000.0, angle_deg=20.0, aperture_radius_mm=15000.0)
    axis = np.array([[0.0, 0.0, 0.0]])
    assert bool(cone.occludes(axis, np.array([0.0, 0.0, 1.0]))[0])
    assert not bool(cone.occludes(axis, np.array([0.0, 0.0, -1.0]))[0])

    for offset, expect in ((-400.0, True), (400.0, False)):
        r = cone.aperture_radius_mm + offset
        start = np.array([[r, 0.0, 0.0]])
        assert bool(cone.occludes(start, np.array([0.0, 0.0, 1.0]))[0]) == expect

    for el, shaded_at_30m in ((9.7, False), (45.0, True)):
        to_sun = sun_vector(90.0, el)
        throw = cone.z_tip_mm / np.tan(np.deg2rad(el)) / 1000.0
        pt = np.array([[-(throw + 8.0) * 1000.0, 0.0, 0.0]])
        assert bool(cone.occludes(pt, to_sun)[0])
        near = np.array([[-30000.0, 0.0, 0.0]])
        assert bool(cone.occludes(near, to_sun)[0]) == shaded_at_30m


# ---------------------------------------------------------------------------
# (b) Fixture parity
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def shading_fixture():
    expected = json.loads((SHADING_ROOT / "expected.json").read_text(encoding="utf-8"))
    occlusion = pd.read_csv(SHADING_ROOT / "occlusion.csv")
    geometry = pd.read_csv(SHADING_ROOT / "geometry.csv")
    return expected, occlusion, geometry


def _rebuild_secondary(expected: dict):
    info = expected["secondary"]
    if info is None:
        return None
    assert info["type"] == "SecondaryCone"
    return SecondaryCone(
        z_tip_mm=info["z_tip_mm"],
        angle_deg=info["angle_deg"],
        aperture_radius_mm=info["aperture_radius_mm"],
    )


@pytest.mark.parametrize(
    "step_key",
    ["20260321_1828", "20260321_0939", "20260321_1235"],
)
def test_shading_fixture_parity(shading_fixture, step_key):
    expected, occlusion, geometry = shading_fixture
    group = geometry[geometry["step_key"] == step_key].reset_index(drop=True)
    assert len(group) == expected["n_geometry_rows"] / 3

    field = HeliostatField(
        x_mm=group["x_mm"].to_numpy(float),
        y_mm=group["y_mm"].to_numpy(float),
        ids=group["heliostat_id"].to_numpy(int),
        mirror_width_mm=expected["mirror_width_mm"],
        mirror_height_mm=expected["mirror_height_mm"],
    )
    neighbours = neighbour_pairs(field, expected["search_radius_mm"])

    rot_az = group["rot_az_deg"].to_numpy(float)
    rot_el = group["rot_el_deg"].to_numpy(float)
    aims = group[["aim_x_mm", "aim_y_mm", "aim_z_mm"]].to_numpy(float)

    geoms, aim_points = build_geometries(
        field, rot_az, rot_el, aims, pedestal_height_mm=expected["pedestal_height_mm"]
    )

    sun_row = next(s for label, s in expected["sun_positions"].items() if s["key"] == step_key)
    secondary = _rebuild_secondary(expected)

    eta_shade, eta_block, eta_secondary = shading_blocking(
        geoms,
        aim_points,
        sun_row["solar_az_deg"],
        sun_row["solar_el_deg"],
        neighbours,
        secondary=secondary,
    )
    eta_union = occlusion_efficiency(
        geoms,
        aim_points,
        sun_row["solar_az_deg"],
        sun_row["solar_el_deg"],
        neighbours,
        secondary=secondary,
    )

    got = pd.DataFrame(
        {
            "heliostat_id": field.ids,
            "eta_shade": eta_shade,
            "eta_block": eta_block,
            "eta_secondary": eta_secondary,
            "eta_union": eta_union,
        }
    ).set_index("heliostat_id")

    want = occlusion[occlusion["step_key"] == step_key].set_index("heliostat_id")
    assert len(want) == 15

    for col in ("eta_shade", "eta_block", "eta_secondary", "eta_union"):
        np.testing.assert_allclose(
            got.loc[want.index, col].to_numpy(),
            want[col].to_numpy(),
            atol=1e-9,
            rtol=0,
            err_msg=f"{col} mismatch at step {step_key}",
        )


# ---------------------------------------------------------------------------
# (c) Union vs product regression
# ---------------------------------------------------------------------------


def test_union_exceeds_product_under_overlapping_occlusion():
    """One neighbour that shades AND blocks the SAME patch of the target's
    aperture: eta_shade * eta_block treats the two losses as independent and
    removes that overlapping patch twice, understating eta relative to the
    true union.

    The aim point here is placed roughly along the sun direction from the
    target (not a physically focused aim point) purely so the shaded and
    blocked regions coincide by construction, isolating the union-vs-product
    difference from any question of how much the two regions happen to
    overlap in a real, focused scene.
    """
    hw, hh = 2500.0, 1500.0
    target = MirrorGeometry.build(0.0, 0.0, 8.0, 45.0, hw, hh)
    to_sun = sun_vector(90.0, 45.0)
    aim = target.centre + to_sun * 100000.0

    # A single neighbour, up-sun and (because aim ~ to_sun) up-beam too,
    # shifted half a mirror-width sideways so it covers part -- not all --
    # of the aperture, which is what makes eta_shade and eta_block partial
    # (not both driven to 0, where union and product would coincide).
    occ_centre = target.centre + to_sun * 6000.0 + target.u * hw
    occluder = MirrorGeometry(
        centre=occ_centre,
        normal=target.normal,
        u=target.u,
        v=target.v,
        half_width=hw,
        half_height=hh,
    )
    neighbours = [np.array([1]), np.array([])]
    geoms = [target, occluder]
    aims = np.tile(aim, (2, 1))

    eta_shade, eta_block, _ = shading_blocking(geoms, aims, 90.0, 45.0, neighbours)
    eta_union = occlusion_efficiency(geoms, aims, 90.0, 45.0, neighbours)

    # Sanity: this case actually occludes a meaningful, partial share.
    assert 0.1 < eta_shade[0] < 0.9
    assert 0.1 < eta_block[0] < 0.9

    product = eta_shade[0] * eta_block[0]
    assert eta_union[0] > product
    assert eta_union[0] - product > 1e-3
